package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'DpaTestRuntimeGitConnector'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("DpaTestRuntimeGitConnector")) {
    val expected = GitVcsRoot({
        id("DpaTestRuntimeGitConnector")
        name = "DPA Test Runtime (github) master"
        url = "https://github.com/solarwinds/dpa-test-runtime.git"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = uploadedKey {
            uploadedKey = "TeamCity Access to GitHub"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "shanas-swi"
            password = "credentialsJSON:bf61d350-be02-4443-bc11-aea55db613a2"
        }
        param("teamcitySshKey", "")
    }

}
